### ISSUE TITLE
Problems in training

### ISSUE THREAD

**Issue by Ayanami2019** [aim-uofa/DyCo3D#5]
Thank you for sharing the code. I would like to ask about some of the problems I encountered when running your code. What is the upper limit for the number of iterations of the code? For data of different batch sizes, it seems that the upper limit of iteration is 30k times. Does it mean that the larger batch size will lead to more training times? I would like to ask what your specific settings are during training.

**Comment by tonghe90** [comment]
@Ayanami2019 The iteration is fixed to a number, e.g. 30k, or 50k, no matter what the batch size is. The training in our experiments are: batch size 9, with 3 GPUs.

**Comment by Ayanami2019** [comment]
Thanks for your answer, but I still don't understand. If the batchsize used is 4, then len(train_loader)=300, which means that it takes 300 iterations to complete one training for all scans. If the batchsize is 3, 400 iterations are required to complete one training. In this way, if a fixed upper limit of iteration (such as 30k) is set, the number of training times of the dataset is actually different.

**Comment by tonghe90** [comment]
@Ayanami2019 Actually, the iteration of 30k is irrelevant to the batch size. Each iter, the model processes "batch_size" samples.

**Comment by Ayanami2019** [comment]
Maybe I made a mistake. Finally, I would like to ask again, does each iteration in your code handle all data or just one batchsize data?

**Comment by tonghe90** [comment]
@Ayanami2019 I see, I didn't change the name from PointGroup, which should be the iteration, instead of epoch. So in each iteration, it handles just one batch size data.

**Comment by Ayanami2019** [comment]
OK, thanks for your answer.
